id: PCA667428
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: pt
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    385f14abdd90485285f5d247f14a02de:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    8a0ba49e461044fe9c3d8a7e2c9340fe:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    71cbe5175a5848cda0ac7037aee56741:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    f1b4a9e6f463408190c7cc0fc6f23359:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    d6551d3f8eed4fe5aab83acbc4b9db41:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    9cf9c0250aa54d2d9799c22bb57d6050:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    c831c9415f69427092dd61642f28c620:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    1b71a040e3814a42b8e799d76bdda5cd:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    e1cd7c92ba2446fc90b7e0d1f5f43e9a:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    28b873d681df497f82c61487e1f8ba85:
      title: The Lament of Rudra
      parent: Confession
    18ab1383be73463280237a221724c829:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    b472f2f1f0fc47cdbe67288a4996a2aa:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    dba606c90eb64831a3f8ee790147b38a:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    5f76e0defed945b4bdc97e6a21ce623a:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    61d440319bfe4d7bb01d2406910ebeaf:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    2e365298fef64acebdc07891f60ef3d3:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    8fd1b9bdc039436e83200cffd1ba8eb0:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    a410eb6b16c2498f924eacd7481d4174:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    2074d50f79374d0abeac361c0f1ed9ed:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    0f7f999f388e47a394d9778022165c11:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    cf64e5069dd04ffd9832f9634721b841:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    afacf79999dd49f2910a9ba80e5edb9e:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    78dfe2153b794164bf20f881973e9905:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    9fd01259b6f04c2291a3f95c2924a97e:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    c6b5341210b64de8ac55ba8c2d20f4db:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    d784f14b59f04c699e8494a2670523de:
      title: The Twenty-Eight Commitments
      parent: Tantra
    acfa4987be1e402f8df79086ae3f842c:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.945951'
last_modified_at: '2022-02-28T22:46:47.945954'
